// this code is autogenerated using ansvia-vscode extension.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for Session
@immutable
class Session extends Equatable {
  final String token;

  const Session(this.token);

  @override
  List<Object> get props => [token];

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = {};
    data["access_token"] = token;
    return data;
  }

  static Session fromMap(Map<String, dynamic> data) {
    return Session(data['access_token'] as String);
  }

  Session copy({String? token}) {
    return Session(token ?? this.token);
  }
}
